# Generated by Django 5.0.7 on 2025-02-08 07:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
