# Generated by Django 5.0.7 on 2025-02-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_lesson_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="instructor",
            field=models.TextField(),
        ),
    ]
