# Generated by Django 5.0.7 on 2025-02-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_course_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="pdf_material",
            field=models.FileField(blank=True, null=True, upload_to="course_pdfs/"),
        ),
    ]
