# Generated by Django 5.0.7 on 2025-02-08 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_usercoursecompletion"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserCourseCompletion",
        ),
    ]
