# Generated by Django 5.0.7 on 2025-02-09 16:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_delete_usercoursecompletion"),
    ]

    operations = [
        migrations.CreateModel(
            name="register_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", ckeditor.fields.RichTextField()),
                ("email", models.EmailField(max_length=254)),
                ("passw", models.CharField(max_length=40)),
                ("cpassw", models.CharField(max_length=40)),
                ("phone_no", models.CharField(blank=True, max_length=100, null=True)),
                ("Address", models.CharField(blank=True, max_length=100, null=True)),
                ("pincode_no", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "date_of_birth",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("Bio", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "image_ed",
                    models.ImageField(blank=True, null=True, upload_to="data"),
                ),
            ],
        ),
    ]
