# Generated by Django 5.0.7 on 2025-02-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_course_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="register_model",
            name="purchased_courses",
            field=models.ManyToManyField(blank=True, to="courses.course"),
        ),
    ]
