# Generated by Django 5.0.7 on 2025-02-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0012_register_model_purchased_courses"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="pdf_material",
            field=models.FileField(blank=True, null=True, upload_to="course_pdfs/"),
        ),
    ]
